# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LRMultiClass_c <- function(X, y, beta_init, numIter = 50L, eta = 0.1, lambda = 1) {
    .Call(`_GroupHW_LRMultiClass_c`, X, y, beta_init, numIter, eta, lambda)
}

MyKmeans_c <- function(X, K, M, numIter = 100L) {
    .Call(`_GroupHW_MyKmeans_c`, X, K, M, numIter)
}

